<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Gateway URI
    |--------------------------------------------------------------------------
    |
    | This value is the URL of the API gateway. This value is used for
    | redirects in OAuth2 authorize endpoint.
    |
    */

    'gateway' => env('API_GATEWAY_URI', 'http://localhost'),

    /*
    |--------------------------------------------------------------------------
    | Provision Key
    |--------------------------------------------------------------------------
    |
    | This key is generated by Kong when OAuth was added as a plugin to the
    | service.
    |
    */

    'provision_key' => env('API_PROVISION_KEY'),

    /*
    |--------------------------------------------------------------------------
    | API path
    |--------------------------------------------------------------------------
    |
    | The path of the API resource.
    |
    */

    'path' => env('API_PATH', '/'),

    /*
    |--------------------------------------------------------------------------
    | Client API path
    |--------------------------------------------------------------------------
    |
    | The path of the API resource for OAuth2 clients.
    |
    */

    'client_path' => env('API_CLIENT_PATH', '/oauth2'),

    /*
    |--------------------------------------------------------------------------
    | Scope API path
    |--------------------------------------------------------------------------
    |
    | The path of the API resource for OAuth2 scopes.
    |
    */

    'scope_path' => env('API_SCOPE_PATH', '/oauth2/scopes'),
];
